export const FETCH_STAFF_BEGIN = 'FETCH_STAFF_BEGIN'
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'
export const FETCH_STAFF_DETAIL_SUCCESS = 'FETCH_STAFF_DETAIL_SUCCESS'
export const FETCH_STAFF_FAILURE = 'FETCH_STAFF_FAILURE'

export const FETCH_COURSES_BEGIN = 'FETCH_COURSES_BEGIN'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_LOCATIONS_BEGIN = 'FETCH_LOCATIONS_BEGIN'
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE'

export const GET_CURRENT_SIDE_MENU = 'GET_CURRENT_SIDE_MENU'

export const FETCH_UPLOAD_IMAGES = 'FETCH_UPLOAD_IMAGES'

