export const FETCH_STAFF_BEGIN = 'FETCH_STAFF_BEGIN'
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'
export const FETCH_STAFF_FAILURE = 'FETCH_STAFF_FAILURE'

export const FETCH_COURSES_BEGIN = 'FETCH_COURSES_BEGIN'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'